apiVersion: v1
kind: Service
metadata:
  name: quarkus-service
spec:
  selector:
    service: quarkus
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000
      name: global
    - protocol: TCP
      port: 81
      targetPort: 2040
      nodePort: 30001
      name: grpc
  type: NodePort
